apiVersion: v2
name: golangapi
description: A Helm chart for golang API application

type: application
version: 0.1.0
appVersion: 1.16.0



dependencies:
  - name: mysql
    repository: "https://charts.bitnami.com/bitnami"
    version: "8.3.0"