apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "golangapi-chart.name" . }}-deployment 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "golangapi-chart.name" . }}-golangapi
  template:
    metadata:
      labels:
        app: {{ include "golangapi-chart.name" . }}-golangapi
    spec:
      containers:
        - name: goapi 
          image: {{ .Values.image }}
          env:
            - name: DBUSER
              value: {{ .Values.mysql.auth.username | quote}}
            - name: DBPASS
              value: {{ .Values.mysql.auth.password | quote }}
            - name: DBHOST
              value: {{ include "mysql.fullyname" . -}}.default.svc.cluster.local
            - name: DBPORT
              value: {{ .Values.Dbport | quote }}
            - name: DBNAME
              value: {{ .Values.mysql.auth.database | quote }}
            - name: DBTABLE
              value: {{ .Values.Dbtable | quote }}
