apiVersion: v1
kind: Service
metadata:
  name: {{ include "golangapi-chart.name" . }}-service
spec:
  type: NodePort
  selector:
    app: {{ include "golangapi-chart.name" . }}-golangapi
  ports:
    - port: 8080
      targetPort: 8080
